/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        // Obsidian Maroon Design System
        'obsidian': '#0B0B0B',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3A3939',
        'surface-container': '#201F1F',
        'surface-container-low': '#1C1B1B',
        'surface-container-high': '#2A2A2A',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0E0E0E',
        'surface-variant': '#353534',
        'primary': '#FFB2B6',
        'primary-container': '#5A0F1C',
        'primary-fixed': '#FFDADB',
        'primary-fixed-dim': '#FFB2B6',
        'on-primary': '#5F131F',
        'on-primary-fixed': '#40000D',
        'on-primary-container': '#DE757D',
        'on-primary-fixed-variant': '#7D2A34',
        'secondary': '#C7C6C6',
        'secondary-container': '#484949',
        'secondary-fixed': '#E3E2E2',
        'secondary-fixed-dim': '#C7C6C6',
        'on-secondary': '#2F3131',
        'on-secondary-container': '#B8B8B8',
        'on-secondary-fixed': '#1A1C1C',
        'on-secondary-fixed-variant': '#464747',
        'tertiary': '#A3CED2',
        'tertiary-container': '#003336',
        'tertiary-fixed': '#BEEBEE',
        'tertiary-fixed-dim': '#A3CED2',
        'on-tertiary': '#043639',
        'on-tertiary-container': '#719C9F',
        'on-tertiary-fixed': '#002022',
        'on-tertiary-fixed-variant': '#224D50',
        'on-surface': '#E5E2E1',
        'on-surface-variant': '#DBC0C1',
        'on-background': '#E5E2E1',
        'outline': '#A38B8C',
        'outline-variant': '#554243',
        'inverse-surface': '#E5E2E1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#9B414A',
        'surface-tint': '#FFB2B6',
        'error': '#FFB4AB',
        'error-container': '#93000A',
        'on-error': '#690005',
        'on-error-container': '#FFDAD6',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
