"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, ArrowRight, Code2, LineChart, Briefcase, Boxes, Terminal, Zap, ShieldCheck, ChevronLeft, ChevronRight, Rocket, Presentation, Target, Palette, Sun, Moon } from "lucide-react";
import { generateId } from "@/lib/utils";
import RobotAgent from "@/components/RobotAgent";
import XcelerateLogo from "@/components/XcelerateLogo";

const PLACEHOLDERS = [
  "Build an AI video repurposing platform for creators...",
  "Launch a zero-sugar hydration brand for gamers...",
  "Create an automated tax OS for remote freelancers...",
  "Build a multi-agent customer success tool for Shopify...",
];

function Meteors({ number = 20 }: { number?: number }) {
  const [styles, setStyles] = useState<{ top: string; left: string; animationDelay: string; animationDuration: string }[]>([]);

  useEffect(() => {
    const generatedStyles = Array.from({ length: number }).map(() => ({
      top: Math.floor(Math.random() * 100) + "%",
      left: Math.floor(Math.random() * 100) + "%",
      animationDelay: Math.random() * 3 + "s",
      animationDuration: Math.random() * 8 + 3 + "s",
    }));
    setTimeout(() => setStyles(generatedStyles), 0);
  }, [number]);

  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
      {styles.map((style, idx) => (
        <span
          key={idx}
          className="animate-meteor-effect absolute top-1/2 left-1/2 h-[0.1rem] w-[0.1rem] rounded-[9999px] bg-slate-400 shadow-[0_0_0_1px_#ffffff10] rotate-[215deg]"
          style={style}
        >
          <div className="pointer-events-none absolute top-1/2 -z-10 h-[1px] w-[50px] -translate-y-1/2 bg-gradient-to-r from-slate-400 to-transparent" />
        </span>
      ))}
    </div>
  );
}

const CodeVisual = () => (
  <div className="w-full h-full min-h-[140px] bg-zinc-950 dark:bg-black/60 rounded-xl border border-zinc-800 dark:border-white/5 p-3.5 font-mono text-[9px] text-zinc-400 overflow-hidden relative select-none">

    <div className="flex items-center gap-1.5 mb-2 pb-1 border-b border-zinc-800 dark:border-white/5">
      <div className="w-1.5 h-1.5 rounded-full bg-red-500/80"></div>
      <div className="w-1.5 h-1.5 rounded-full bg-yellow-500/80"></div>
      <div className="w-1.5 h-1.5 rounded-full bg-green-500/80"></div>
      <span className="text-[8px] text-zinc-500 ml-1">app/page.tsx</span>
    </div>
    <div className="space-y-1 text-left">
      <p className="text-blue-400">import <span className="text-white">React</span> from <span className="text-green-400">&apos;react&apos;</span>;</p>
      <p className="text-blue-400">export default function <span className="text-purple-400">App</span>() &#123;</p>
      <p className="pl-2 text-zinc-500">{"// Generated by Xcelerate Swarm"}</p>
      <p className="pl-2 text-blue-400">return (</p>
      <p className="pl-4 text-purple-400">&lt;<span className="text-blue-400">div</span> className=<span className="text-green-400">&quot;bg-black text-white&quot;</span>&gt;</p>
      <p className="pl-6 text-purple-400">&lt;<span className="text-blue-400">h1</span>&gt;Velocity SaaS&lt;/<span className="text-blue-400">h1</span>&gt;</p>
      <p className="pl-4 text-purple-400">&lt;/<span className="text-blue-400">div</span>&gt;</p>
      <p className="pl-2 text-blue-400">);</p>
      <p className="text-blue-400">&#125;</p>
    </div>
    <div className="absolute bottom-1.5 right-1.5 opacity-30">
      <RobotAgent agentId="product" size={60} typing={true} />
    </div>
  </div>
);

const FinanceVisual = () => (
  <div className="w-full h-24 flex items-end justify-between px-2 pt-6 select-none relative overflow-hidden bg-white dark:bg-black/40 border border-zinc-200 dark:border-white/5 rounded-xl shadow-sm dark:shadow-none">
    <div className="absolute inset-0 bg-gradient-to-t from-blue-500/10 dark:from-blue-500/5 to-transparent z-0" />
    <svg className="w-full h-full overflow-visible z-10" viewBox="0 0 100 40">
      <defs>
        <linearGradient id="chart-glow" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#3B82F6" stopOpacity="0.4" />
          <stop offset="100%" stopColor="#3B82F6" stopOpacity="0.0" />
        </linearGradient>
      </defs>
      <path
        d="M 0,40 Q 20,35 40,25 T 80,12 T 100,2 L 100,40 L 0,40 Z"
        fill="url(#chart-glow)"
      />
      <path
        d="M 0,40 Q 20,35 40,25 T 80,12 T 100,2"
        fill="none"
        stroke="#3B82F6"
        strokeWidth="2"
      />
      <circle cx="40" cy="25" r="1.5" fill="#3B82F6" />
      <circle cx="80" cy="12" r="1.5" fill="#3B82F6" />
      <circle cx="100" cy="2" r="2" fill="#3B82F6" className="animate-pulse" />
    </svg>
  </div>
);

const SwarmVisual = () => (
  <div className="w-full h-24 flex items-center justify-center gap-2 relative overflow-hidden select-none bg-white dark:bg-black/40 border border-zinc-200 dark:border-white/5 rounded-xl shadow-sm dark:shadow-none">
    <div className="absolute inset-0 flex items-center justify-center opacity-25">
      <svg className="w-full h-full overflow-visible" viewBox="0 0 200 80">
        <path d="M 30,40 L 80,40 M 80,40 L 120,40 M 120,40 L 170,40 M 80,40 L 100,15 L 120,40 M 80,40 L 100,65 L 120,40" className="stroke-zinc-400 dark:stroke-white" strokeWidth="1" strokeDasharray="3 3" />
      </svg>
    </div>
    <div className="flex gap-2.5 z-10">
      {["ceo", "product", "growth", "operations"].map((id) => (
        <div key={id} className="w-7 h-7 rounded bg-zinc-100 dark:bg-white/5 border border-zinc-200 dark:border-white/10 flex items-center justify-center overflow-hidden">
          <RobotAgent agentId={id} size={24} headOnly={true} />
        </div>
      ))}
    </div>
  </div>
);

const GtmVisual = () => (
  <div className="w-full h-full min-h-[140px] bg-white dark:bg-black/60 rounded-xl border border-zinc-200 dark:border-white/5 p-4 flex flex-col justify-between select-none relative overflow-hidden">

    <div className="space-y-2">
      <div className="flex justify-between items-center text-[10px]">
        <span className="text-zinc-600 dark:text-zinc-500 font-medium">Outreach Funnel</span>
        <span className="text-green-600 dark:text-green-400 font-bold">+14.2%</span>
      </div>
      <div className="space-y-1.5 text-left">
        {[
          { label: "Target Creators", width: "90%", color: "bg-blue-500" },
          { label: "Sent Sequenced DMs", width: "70%", color: "bg-purple-500" },
          { label: "Acquired Leads", width: "45%", color: "bg-pink-500" }
        ].map((bar, i) => (
          <div key={i} className="space-y-0.5">
            <div className="flex justify-between text-[8px] text-zinc-600 dark:text-zinc-400">
              <span>{bar.label}</span>
              <span>{bar.width}</span>
            </div>
            <div className="h-1 bg-zinc-100 dark:bg-white/5 rounded-full overflow-hidden">
              <div
                className={`h-full ${bar.color} rounded-full`}
                style={{ width: bar.width }}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
    <div className="flex gap-1.5 mt-2">
      {["SEO", "Soc", "Ads"].map((tag) => (
        <span key={tag} className="text-[8px] font-mono text-zinc-600 dark:text-zinc-400 px-1.5 py-0.5 rounded border border-zinc-200 dark:border-white/5 bg-zinc-100 dark:bg-white/5">{tag}</span>
      ))}
    </div>
  </div>
);




const MvpSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 font-mono text-[9px] text-zinc-400 justify-between select-none bg-zinc-950 dark:bg-black/40">
    <div className="flex items-center justify-between border-b border-zinc-800 dark:border-white/5 pb-2">
      <span className="text-[8px] text-blue-400">api/auth/route.ts</span>
      <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
    </div>
    <div className="space-y-1 mt-1 text-left flex-1">
      <p className="text-zinc-300 dark:text-zinc-400"><span className="text-purple-400">export async function</span> POST(req: Request) &#123;</p>
      <p className="pl-3 text-zinc-300 dark:text-zinc-400">const body = <span className="text-blue-400">await</span> req.json();</p>
      <p className="pl-3 text-zinc-300 dark:text-zinc-400">const user = <span className="text-blue-400">await</span> db.user.create(&#123; data: body &#125;);</p>
      <p className="pl-3 text-zinc-300 dark:text-zinc-400">return NextResponse.json(&#123; user &#125;);</p>
      <p className="text-zinc-300 dark:text-zinc-400">&#125;</p>
    </div>
    <div className="flex justify-between items-center text-[7px] border-t border-zinc-800 dark:border-white/5 pt-2">
      <span className="text-zinc-500">Database connected</span>
      <span className="text-green-500">✓ Ready</span>
    </div>
  </div>
);

const PitchDeckSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 justify-between bg-white dark:bg-zinc-950 select-none relative overflow-hidden text-left">
    <div className="absolute top-0 right-0 w-16 h-16 bg-blue-500/10 rounded-full blur-xl" />
    <div className="space-y-1">
      <span className="text-[8px] font-mono text-zinc-500 dark:text-zinc-600 tracking-widest uppercase">Slide 04 / Market Size</span>
      <h4 className="text-xs font-bold text-zinc-900 dark:text-white tracking-tight leading-tight mt-0.5">Addressing the $12B TAM</h4>
    </div>

    <div className="grid grid-cols-3 gap-2 mt-2 flex-1 items-end">
      <div className="space-y-1">
        <div className="h-10 bg-zinc-100 dark:bg-white/5 border border-zinc-200 dark:border-white/10 rounded flex items-center justify-center text-[9px] font-bold text-zinc-700 dark:text-zinc-300">SOM</div>
        <p className="text-[7px] text-zinc-500 text-center">$1.2B</p>
      </div>
      <div className="space-y-1">
        <div className="h-14 bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 rounded flex items-center justify-center text-[9px] font-bold text-blue-600 dark:text-blue-400">SAM</div>
        <p className="text-[7px] text-blue-600 dark:text-blue-400 text-center">$4.5B</p>
      </div>
      <div className="space-y-1">
        <div className="h-16 bg-purple-50 dark:bg-purple-500/10 border border-purple-200 dark:border-purple-500/20 rounded flex items-center justify-center text-[9px] font-bold text-purple-600 dark:text-purple-400">TAM</div>
        <p className="text-[7px] text-purple-600 dark:text-purple-400 text-center">$12B</p>
      </div>
    </div>
  </div>
);

const GtmSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-3 justify-between bg-white dark:bg-black/40 select-none relative overflow-hidden text-left">
    <div className="flex items-center gap-2 mb-1.5">
      <div className="w-5 h-5 rounded-full bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-white/10 flex items-center justify-center text-[9px] font-bold text-zinc-900 dark:text-white">M</div>
      <div className="flex flex-col">
        <span className="text-[9px] font-bold text-zinc-900 dark:text-white leading-tight">maya_growth</span>
        <span className="text-[7px] text-zinc-500">Instagram Reels campaign</span>
      </div>
    </div>

    <div className="flex-1 bg-zinc-100 dark:bg-zinc-900/60 rounded border border-zinc-200 dark:border-white/5 p-2 flex flex-col justify-between">
      <p className="text-[9px] text-zinc-800 dark:text-zinc-300 font-semibold leading-snug">&ldquo;POV: You build a whole SaaS with one command.&rdquo;</p>
      <div className="flex items-center justify-between text-[7px] text-zinc-500 mt-2">
        <span>Target Hook: <strong className="text-zinc-700 dark:text-zinc-300">92% Engagement</strong></span>
        <span className="text-zinc-500 dark:text-zinc-400">14k views</span>
      </div>
    </div>

    <div className="flex justify-between items-center mt-1.5 text-[8px] text-zinc-500">
      <span>CTR: <strong className="text-green-600 dark:text-green-400">4.8%</strong></span>
      <span>RoAS: <strong className="text-blue-600 dark:text-blue-400">3.5x</strong></span>
    </div>
  </div>
);

const BrandSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 justify-between bg-white dark:bg-zinc-950 select-none text-left">
    <div className="flex justify-between items-start">
      <div className="space-y-1">
        <span className="text-[8px] font-mono text-zinc-500 dark:text-zinc-600 tracking-wider">Style System</span>
        <h4 className="text-xs font-bold text-zinc-900 dark:text-white">Aa <span className="font-light text-zinc-500 dark:text-zinc-400">Outfit Bold</span></h4>
      </div>
      <div className="flex gap-1">
        {["#000000", "#3B82F6", "#A855F7"].map((hex) => (
          <div key={hex} className="flex flex-col items-center gap-0.5">
            <div className="w-4 h-4 rounded-full border border-zinc-200 dark:border-white/10" style={{ background: hex }} />
            <span className="text-[6px] font-mono text-zinc-500">{hex}</span>
          </div>
        ))}
      </div>
    </div>

    <div className="h-12 border border-dashed border-zinc-300 dark:border-white/10 rounded flex items-center justify-center relative overflow-hidden bg-zinc-50 dark:bg-black/40">
      <svg className="w-16 h-16 text-zinc-200 dark:text-white/10 absolute -rotate-12" viewBox="0 0 100 100">
        <path d="M 50,10 L 90,90 L 10,90 Z" fill="none" stroke="currentColor" strokeWidth="2" />
      </svg>
      <div className="flex items-center gap-2 z-10">
        <XcelerateLogo size={22} className="text-zinc-900 dark:text-white" />
        <span className="text-[10px] font-bold text-zinc-900 dark:text-white tracking-widest uppercase">Xcelerate</span>
      </div>
    </div>
  </div>

);

function HowItHelpsSection() {
  const SKILLS = [
    {
      id: "mvp",
      tag: "/build-mvp",
      title: "Build an MVP",
      desc: "Generate a complete, deployable Next.js application with authentication, database schemas, and API routes in minutes.",
      apps: ["Nx", "DB", "Api", "Ts"],
      visual: <MvpSkillVisual />
    },
    {
      id: "deck",
      tag: "/write-pitch-deck",
      title: "Write a Pitch Deck",
      desc: "Create a compelling narrative with automated financial projections, market sizing, and competitor analysis.",
      apps: ["Doc", "Xls", "Pdf"],
      visual: <PitchDeckSkillVisual />
    },
    {
      id: "gtm",
      tag: "/launch-campaign",
      title: "Launch Go-To-Market",
      desc: "Generate targeted SEO content, social media clusters, and personalized outreach sequences for early adopters.",
      apps: ["SEO", "Soc", "Ads"],
      visual: <GtmSkillVisual />
    },
    {
      id: "brand",
      tag: "/design-brand",
      title: "Design Brand Identity",
      desc: "Create logos, color palettes, typography systems, and brand guidelines that feel premium and modern.",
      apps: ["Fig", "Svg", "Css"],
      visual: <BrandSkillVisual />
    }
  ];

  return (
    <section className="relative z-10 py-24 px-4 md:px-6 max-w-7xl mx-auto border-t border-[var(--border)]">
      <div className="text-center mb-16">
        <span className="text-xs font-mono uppercase tracking-widest text-[var(--muted)] font-bold mb-3 block">
          Specialized Workflows
        </span>
        <h2 className="text-3xl md:text-5xl lg:text-6xl font-extrabold tracking-tight mb-4 text-gradient">
          How Xcelerate can help you.
        </h2>
        <p className="text-[var(--muted)] text-lg md:text-xl font-medium max-w-2xl mx-auto">
          Explore specialized capabilities designed to help every founder build, launch, and scale their ideas faster than ever before.
        </p>
      </div>

      {/* ONE Unified Continuous Grid Canvas for Capabilities */}
      <div className="w-full border border-[var(--border)] rounded-2xl md:rounded-3xl overflow-hidden bg-[var(--surface)] grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 divide-y md:divide-y-0 md:divide-x divide-[var(--border)] relative">

        {SKILLS.map((skill) => (
          <div key={skill.id} className="p-6 md:p-8 flex flex-col justify-between group hover:bg-[var(--background)]/50 transition-colors duration-300">
            <div>
              {/* Tag Header */}
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[var(--background)] border border-[var(--border)] text-[10px] font-mono font-medium text-[var(--muted)] mb-6">
                <span className="w-1.5 h-1.5 rounded-full bg-[var(--accent)]" />
                {skill.tag}
              </div>

              {/* Title & Desc */}
              <h3 className="text-xl font-bold mb-3 tracking-tight text-[var(--foreground)] group-hover:text-[var(--accent)] transition-colors">
                {skill.title}
              </h3>
              <p className="text-[var(--muted)] text-sm leading-relaxed mb-6 font-medium">
                {skill.desc}
              </p>
            </div>

            {/* Embedded Visual Module */}
            <div className="space-y-4 mt-2">
              <div className="w-full h-44 rounded-xl border border-[var(--border)] overflow-hidden bg-[var(--background)]">
                {skill.visual}
              </div>

              {/* Tech Apps Pill List */}
              <div className="flex gap-1.5 items-center">
                {skill.apps.map((app) => (
                  <div key={app} className="px-2.5 py-1 rounded-md bg-[var(--background)] border border-[var(--border)] text-[10px] font-mono font-bold text-[var(--muted)]">
                    {app}
                  </div>
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}


const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.3,
    }
  }
};

const robotVariants = {
  hidden: {
    opacity: 0,
    scale: 0.3,
    y: 40,
    filter: "blur(8px)"
  },
  visible: {
    opacity: 1,
    scale: 1,
    y: 0,
    filter: "blur(0px)",
    transition: {
      type: "spring" as const,
      stiffness: 100,
      damping: 15
    }
  }
};

export default function LandingPage() {
  const router = useRouter();
  const [idea, setIdea] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [placeholderIndex, setPlaceholderIndex] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [theme, setTheme] = useState<"light" | "dark">("dark");

  useEffect(() => {
    const savedTheme = (localStorage.getItem("theme") as "light" | "dark") || "dark";
    setTheme(savedTheme);
    if (savedTheme === "light") {
      document.documentElement.classList.add("light");
    } else {
      document.documentElement.classList.remove("light");
    }
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === "dark" ? "light" : "dark";
    setTheme(newTheme);
    localStorage.setItem("theme", newTheme);
    if (newTheme === "light") {
      document.documentElement.classList.add("light");
    } else {
      document.documentElement.classList.remove("light");
    }
  };
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isTyping) return;
    const interval = setInterval(() => {
      setPlaceholderIndex((i) => (i + 1) % PLACEHOLDERS.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [isTyping]);

  const handleSubmit = (e?: React.FormEvent) => {
    e?.preventDefault();
    if (!idea.trim() || isSubmitting) return;
    setIsSubmitting(true);
    const id = generateId();
    sessionStorage.setItem("xcelerate_idea", idea.trim());
    sessionStorage.setItem("xcelerate_project_id", id);
    router.push(`/workspace/${id}/chat`);
  };

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] relative overflow-hidden font-sans">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-dot-pattern opacity-40 z-0"></div>
      <div className="glow-bg z-0"></div>
      <Meteors number={15} />

      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-[var(--border)] bg-[var(--background)]/75 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5 cursor-pointer" onClick={() => router.push("/")}>
            <XcelerateLogo size={28} className="text-[var(--foreground)]" />
            <span className="font-extrabold text-xl tracking-tight text-[var(--foreground)]">Xcelerate</span>
          </div>

          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-[var(--muted)]">
            <a href="#features" className="hover:text-[var(--foreground)] transition-colors">Features</a>
            <a href="#agents" className="hover:text-[var(--foreground)] transition-colors">AI Swarm</a>
            <a href="#pricing" className="hover:text-[var(--foreground)] transition-colors">Pricing</a>
          </div>
          <div className="flex items-center gap-4">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-full border border-[var(--border)] bg-[var(--surface)] hover:bg-[var(--border)] transition-all text-[var(--muted)] hover:text-[var(--foreground)] flex items-center justify-center shadow-sm"
              aria-label="Toggle Theme"
            >
              {theme === "dark" ? (
                <Sun className="w-4 h-4 text-yellow-400" />
              ) : (
                <Moon className="w-4 h-4 text-blue-500" />
              )}
            </button>
            <button
              onClick={() => router.push("/demo")}
              className="text-sm font-medium text-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
            >
              Live Demo
            </button>
            <button
              onClick={() => inputRef.current?.focus()}
              className="px-4 py-2 rounded-full text-sm font-bold bg-[var(--foreground)] text-[var(--background)] hover:opacity-90 transition-all shadow-sm"
            >
              Start Building
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="relative z-10 pt-44 pb-20 px-6 max-w-5xl mx-auto text-center flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="w-full flex flex-col items-center"
        >
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-[var(--border)] bg-[var(--surface)] text-xs text-[var(--foreground)] mb-8 backdrop-blur-md">
            <Sparkles className="w-3.5 h-3.5 text-blue-400" />
            <span className="font-medium">Xcelerate Swarm v3.4 is live</span>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse ml-1" />
          </div>


          {/* Swarm Cinematic Lineup */}
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="flex justify-center items-center gap-6 md:gap-10 mb-8 mt-2"
          >
            {[
              { id: "ceo", name: "Nova", role: "CEO", yOffset: [-4, 4] },
              { id: "product", name: "Mira", role: "Product", yOffset: [-6, 2] },
              { id: "growth", name: "Ari", role: "Growth", yOffset: [-3, 5] },
              { id: "operations", name: "Noah", role: "Operations", yOffset: [-5, 3] }
            ].map((bot, idx) => (
              <motion.div
                key={bot.id}
                variants={robotVariants}
                animate={{
                  y: bot.yOffset,
                  transition: {
                    duration: 2 + idx * 0.3,
                    repeat: Infinity,
                    repeatType: "reverse",
                    ease: "easeInOut"
                  }
                }}
                className="flex flex-col items-center relative group"
              >
                {/* Floating glow behind robot */}
                <div className="absolute -inset-1 bg-gradient-to-b from-blue-500/10 to-purple-500/10 rounded-full blur-md opacity-0 group-hover:opacity-100 transition duration-500" />
                <RobotAgent agentId={bot.id} size={90} typing={true} />
                <span className="text-[10px] font-bold text-[var(--muted)] mt-2 px-2 py-0.5 rounded-full border border-[var(--border)] bg-[var(--surface)] uppercase tracking-wider group-hover:text-[var(--foreground)] group-hover:border-[var(--border)] transition-colors">
                  {bot.role}
                </span>
              </motion.div>
            ))}
          </motion.div>

          {/* Headline */}
          <h1 className="text-5xl md:text-7xl lg:text-[5rem] font-extrabold tracking-tight mb-8 leading-[1.1] max-w-4xl">
            Build an entire company.<br />
            <span className="text-gradient">With a single prompt.</span>
          </h1>

          {/* Subtitle */}
          <p className="text-lg md:text-xl text-[var(--muted)] max-w-2xl mx-auto mb-12 leading-relaxed font-medium">
            Xcelerate deploys specialized AI Directors—Product, Engineering, Growth, and Finance—to build your startup in parallel.
          </p>

          {/* Hero Input (The Command Bar) */}
          <div className="w-full max-w-3xl mx-auto relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-blue-500 to-purple-600 rounded-2xl blur-md opacity-20 group-focus-within:opacity-60 transition duration-1000 group-hover:opacity-60"></div>
            <form
              onSubmit={handleSubmit}
              className="relative flex items-center bg-[var(--surface)] border border-[var(--border)] rounded-2xl p-2 transition-all duration-300 hover:border-[var(--border)] focus-within:border-[var(--border)]"
            >

              <div className="pl-4 pr-2">
                <Terminal className="w-5 h-5 text-[var(--muted)]" />
              </div>
              <div className="relative w-full h-14 flex items-center">
                <input
                  ref={inputRef}
                  type="text"
                  value={idea}
                  onChange={(e) => {
                    setIdea(e.target.value);
                    setIsTyping(e.target.value.length > 0);
                  }}
                  onFocus={() => setIsTyping(true)}
                  onBlur={() => setIsTyping(idea.length > 0)}
                  className="w-full h-full bg-transparent text-[var(--foreground)] text-lg font-medium outline-none placeholder:text-transparent"
                  placeholder=""
                />
                {!idea && (
                  <div className="absolute inset-0 flex items-center pointer-events-none text-[var(--muted)] text-lg font-medium opacity-60">
                    <AnimatePresence mode="wait">
                      <motion.span
                        key={placeholderIndex}
                        initial={{ opacity: 0, y: 4 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -4 }}
                        transition={{ duration: 0.2 }}
                      >
                        {PLACEHOLDERS[placeholderIndex]}
                      </motion.span>
                    </AnimatePresence>
                  </div>
                )}
              </div>
              <button
                type="submit"
                disabled={!idea.trim() || isSubmitting}
                className="ml-2 mr-1 px-8 h-12 rounded-xl bg-[var(--foreground)] text-[var(--background)] font-bold hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
              >
                {isSubmitting ? (
                  <div className="w-4 h-4 border-2 border-black/20 border-t-black rounded-full animate-spin" />
                ) : (
                  <>
                    Build <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Quick links */}
          <div className="mt-8 flex items-center gap-4 text-sm text-[var(--muted)] font-medium">
            <span>Press <kbd className="px-1.5 py-0.5 rounded bg-[var(--surface)] text-[var(--foreground)] font-mono text-xs mx-1 border border-[var(--border)]">Enter</kbd> to execute</span>
            <span>•</span>
            <button onClick={() => { setIdea(PLACEHOLDERS[0]); setIsTyping(true); }} className="hover:text-[var(--foreground)] transition-colors">Try an example</button>
          </div>
        </motion.div>
      </main>

      {/* Trusted By Banner */}
      <section className="relative z-10 border-y border-[var(--border)] bg-[var(--surface)] py-8 overflow-hidden mb-24">
        <div className="max-w-7xl mx-auto px-6 flex flex-col items-center">
          <p className="text-xs uppercase tracking-widest text-[var(--muted)] font-bold mb-6 flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-[var(--accent)]" /> Trusted by 10,000+ AI Native Founders
          </p>
          <div className="flex gap-12 text-[var(--muted)] font-bold text-xl md:text-2xl filter grayscale opacity-60 justify-center flex-wrap">
            <span>Stripe</span>
            <span>Vercel</span>
            <span>Supabase</span>
            <span>Shopify</span>
            <span>Linear</span>
          </div>
        </div>
      </section>

      {/* Hero Visual Mockup */}
      <section className="relative z-10 px-6 max-w-6xl mx-auto pb-32">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.2 }}
          className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] overflow-hidden animate-float"

        >
          {/* Window Header */}
          <div className="h-12 border-b border-[var(--border)] flex items-center px-4 gap-2 bg-[var(--surface)]">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
            </div>
            <div className="mx-auto px-4 py-1.5 rounded-md bg-[var(--background)] text-xs text-[var(--muted)] font-mono flex items-center gap-2 shadow-inner border border-[var(--border)]">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              xcelerate-workspace.app
            </div>
          </div>
          {/* Window Body */}
          <div className="aspect-[16/9] w-full bg-[var(--background)] p-6 relative overflow-hidden flex flex-col md:flex-row gap-6">
            <div className="flex-1 border border-[var(--border)] rounded-xl bg-[var(--surface)] p-5 flex flex-col shadow-inner">
              <div className="text-xs text-[var(--muted)] font-mono mb-4 border-b border-[var(--border)] pb-2">Terminal Feed</div>
              <div className="space-y-4 font-mono text-[11px] text-[var(--foreground)]">
                <div className="flex gap-2"><span className="text-blue-400">[Product]</span> Generating PRD for AI Video Editor...</div>
                <div className="flex gap-2"><span className="text-green-400">[Engineering]</span> Bootstrapping Next.js 15 repository...</div>
                <div className="flex gap-2"><span className="text-purple-400">[Growth]</span> Mapping 100-creator outreach pipeline...</div>
                <div className="flex gap-2"><span className="text-yellow-400">[Finance]</span> Calculating AWS compute unit margins...</div>
              </div>
            </div>
            <div className="flex-[2] border border-[var(--border)] rounded-xl bg-[var(--surface)] p-6 flex flex-col items-center justify-center relative overflow-hidden shadow-inner min-h-[300px]">
              <div className="absolute top-4 left-4 text-xs font-bold text-[var(--muted)] uppercase tracking-widest flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                <span>Swarm Live Collaboration</span>
              </div>

              <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
                {[
                  { id: "ceo", name: "Nova", role: "AI CEO" },
                  { id: "product", name: "Mira", role: "Product" },
                  { id: "growth", name: "Ari", role: "Growth" },
                  { id: "operations", name: "Noah", role: "Operations" }
                ].map((bot) => (
                  <div key={bot.id} className="flex flex-col items-center p-3 rounded-xl border border-[var(--border)] bg-[var(--background)] hover:bg-[var(--surface)] transition-colors">
                    <RobotAgent agentId={bot.id} size={80} typing={true} />
                    <div className="text-center mt-2">
                      <p className="text-[11px] font-bold text-[var(--foreground)] leading-none">{bot.name}</p>
                      <p className="text-[9px] text-[var(--muted)] mt-1 uppercase tracking-wider">{bot.role}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* How It Helps Section */}
      <HowItHelpsSection />

      {/* Feature Section: GitHub-Style Editorial Unified Grid */}
      <section id="features" className="relative z-10 py-24 px-4 md:px-6 max-w-7xl mx-auto border-t border-[var(--border)]">
        <div className="text-center mb-16">
          <span className="text-xs font-mono uppercase tracking-widest text-[var(--muted)] font-bold mb-3 block">
            AI Infrastructure
          </span>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-extrabold tracking-tight mb-4 text-gradient">
            The autonomous architecture.
          </h2>
          <p className="text-[var(--muted)] text-lg md:text-xl font-medium max-w-2xl mx-auto">
            Built for founders who want to move at the speed of thought.
          </p>
        </div>

        {/* ONE Unified Continuous Grid Canvas */}
        <div className="w-full border border-[var(--border)] rounded-2xl md:rounded-3xl overflow-hidden bg-[var(--surface)] grid grid-cols-1 md:grid-cols-12 divide-y md:divide-y-0 divide-[var(--border)] relative">

          
          {/* Row 1 Container: 12 Cols */}
          <div className="md:col-span-12 grid grid-cols-1 md:grid-cols-12 divide-y md:divide-y-0 md:divide-x divide-[var(--border)] border-b border-[var(--border)]">
            
            {/* Cell 1: Production Code Generation (Asymmetric Wide 7 Cols) */}
            <div className="md:col-span-7 p-8 md:p-12 lg:p-14 flex flex-col justify-between group hover:bg-[var(--background)]/50 transition-colors duration-300">
              <div>
                <div className="w-10 h-10 rounded-xl bg-[var(--background)] border border-[var(--border)] flex items-center justify-center mb-6 text-[var(--foreground)] group-hover:scale-110 transition-transform">
                  <Code2 className="w-5 h-5" />
                </div>
                <h3 className="text-2xl md:text-4xl font-extrabold mb-4 tracking-tight text-[var(--foreground)]">
                  Production Code Generation
                </h3>
                <p className="text-[var(--muted)] text-base md:text-lg leading-relaxed mb-8 max-w-lg font-medium">
                  Not just mockups. Xcelerate writes complete Next.js 15 applications with Tailwind CSS, Supabase databases, and fully typed APIs. Ready to deploy to Vercel with one click.
                </p>
              </div>
              <div className="w-full mt-4">
                <CodeVisual />
              </div>
            </div>

            {/* Cell 2: Financial Modeling (Compact 5 Cols) */}
            <div className="md:col-span-5 p-8 md:p-12 lg:p-14 flex flex-col justify-between group hover:bg-[var(--background)]/50 transition-colors duration-300">
              <div>
                <div className="w-10 h-10 rounded-xl bg-[var(--background)] border border-[var(--border)] flex items-center justify-center mb-6 text-[var(--foreground)] group-hover:scale-110 transition-transform">
                  <LineChart className="w-5 h-5" />
                </div>
                <h3 className="text-2xl md:text-3xl font-extrabold mb-4 tracking-tight text-[var(--foreground)]">
                  Financial Modeling
                </h3>
                <p className="text-[var(--muted)] text-base leading-relaxed mb-8 font-medium">
                  Instant 5-year unit economics, MRR projections, and cap table generation for your pitch deck.
                </p>
              </div>
              <div className="w-full mt-4">
                <FinanceVisual />
              </div>
            </div>

          </div>

          {/* Row 2 Container: 12 Cols */}
          <div className="md:col-span-12 grid grid-cols-1 md:grid-cols-12 divide-y md:divide-y-0 md:divide-x divide-[var(--border)]">
            
            {/* Cell 3: Parallel Agents (Compact 5 Cols) */}
            <div className="md:col-span-5 p-8 md:p-12 lg:p-14 flex flex-col justify-between group hover:bg-[var(--background)]/50 transition-colors duration-300">
              <div>
                <div className="w-10 h-10 rounded-xl bg-[var(--background)] border border-[var(--border)] flex items-center justify-center mb-6 text-[var(--foreground)] group-hover:scale-110 transition-transform">
                  <Boxes className="w-5 h-5" />
                </div>
                <h3 className="text-2xl md:text-3xl font-extrabold mb-4 tracking-tight text-[var(--foreground)]">
                  Parallel Agents
                </h3>
                <p className="text-[var(--muted)] text-base leading-relaxed mb-8 font-medium">
                  4 specialized agents work simultaneously, debating trade-offs and building your startup 4x faster.
                </p>
              </div>
              <div className="w-full mt-4">
                <SwarmVisual />
              </div>
            </div>

            {/* Cell 4: Go-To-Market Automation (Asymmetric Wide 7 Cols) */}
            <div className="md:col-span-7 p-8 md:p-12 lg:p-14 flex flex-col justify-between group hover:bg-[var(--background)]/50 transition-colors duration-300">
              <div>
                <div className="w-10 h-10 rounded-xl bg-[var(--background)] border border-[var(--border)] flex items-center justify-center mb-6 text-[var(--foreground)] group-hover:scale-110 transition-transform">
                  <Briefcase className="w-5 h-5" />
                </div>
                <h3 className="text-2xl md:text-4xl font-extrabold mb-4 tracking-tight text-[var(--foreground)]">
                  Go-To-Market Automation
                </h3>
                <p className="text-[var(--muted)] text-base md:text-lg leading-relaxed mb-8 max-w-lg font-medium">
                  Generate 30-day launch roadmaps, programmatic SEO clusters, and personalized creator outreach DMs instantly.
                </p>
              </div>
              <div className="w-full mt-4">
                <GtmVisual />
              </div>
            </div>

          </div>

        </div>
      </section>


      {/* CTA Section */}
      <section className="relative z-10 py-32 px-6 max-w-4xl mx-auto text-center border-t border-[var(--border)]">
        <h2 className="text-4xl md:text-5xl font-bold tracking-tight mb-6 text-[var(--foreground)]">Stop planning. Start building.</h2>
        <p className="text-[var(--muted)] text-lg mb-8">Join thousands of founders launching their next big idea with Xcelerate.</p>
        <button
          onClick={() => {
            window.scrollTo({ top: 0, behavior: "smooth" });
            setTimeout(() => inputRef.current?.focus(), 800);
          }}
          className="px-8 py-4 rounded-full text-lg font-bold bg-[var(--foreground)] text-[var(--background)] hover:opacity-90 transition-all shadow-sm"
        >
          Create your company now
        </button>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border)] py-12 px-6 bg-[var(--background)]">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2.5">
            <XcelerateLogo size={24} className="text-[var(--foreground)]" />
            <span className="font-bold tracking-tight text-[var(--foreground)]">Xcelerate</span>
          </div>

          <div className="flex items-center gap-6 text-sm text-[var(--muted)] font-medium">
            <span>© {new Date().getFullYear()} Xcelerate Inc.</span>
            <a href="#" className="hover:text-[var(--foreground)] transition-colors">Twitter</a>
            <a href="#" className="hover:text-[var(--foreground)] transition-colors">GitHub</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
