"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, ArrowRight, Code2, LineChart, Briefcase, Boxes, Terminal, Zap, ShieldCheck, ChevronLeft, ChevronRight, Rocket, Presentation, Target, Palette, Sun, Moon } from "lucide-react";
import { generateId } from "@/lib/utils";
import RobotAgent from "@/components/RobotAgent";

const PLACEHOLDERS = [
  "Build an AI video repurposing platform for creators...",
  "Launch a zero-sugar hydration brand for gamers...",
  "Create an automated tax OS for remote freelancers...",
  "Build a multi-agent customer success tool for Shopify...",
];

function Meteors({ number = 20 }: { number?: number }) {
  const [styles, setStyles] = useState<{ top: string; left: string; animationDelay: string; animationDuration: string }[]>([]);

  useEffect(() => {
    const generatedStyles = Array.from({ length: number }).map(() => ({
      top: Math.floor(Math.random() * 100) + "%",
      left: Math.floor(Math.random() * 100) + "%",
      animationDelay: Math.random() * 3 + "s",
      animationDuration: Math.random() * 8 + 3 + "s",
    }));
    setTimeout(() => setStyles(generatedStyles), 0);
  }, [number]);

  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
      {styles.map((style, idx) => (
        <span
          key={idx}
          className="animate-meteor-effect absolute top-1/2 left-1/2 h-[0.1rem] w-[0.1rem] rounded-[9999px] bg-slate-400 shadow-[0_0_0_1px_#ffffff10] rotate-[215deg]"
          style={style}
        >
          <div className="pointer-events-none absolute top-1/2 -z-10 h-[1px] w-[50px] -translate-y-1/2 bg-gradient-to-r from-slate-400 to-transparent" />
        </span>
      ))}
    </div>
  );
}

const CodeVisual = () => (
  <div className="w-full h-full min-h-[140px] bg-black/60 rounded-xl border border-white/5 p-3.5 font-mono text-[9px] text-zinc-400 overflow-hidden shadow-2xl relative select-none">
    <div className="flex items-center gap-1.5 mb-2 pb-1 border-b border-white/5">
      <div className="w-1.5 h-1.5 rounded-full bg-red-500/80"></div>
      <div className="w-1.5 h-1.5 rounded-full bg-yellow-500/80"></div>
      <div className="w-1.5 h-1.5 rounded-full bg-green-500/80"></div>
      <span className="text-[8px] text-zinc-500 ml-1">app/page.tsx</span>
    </div>
    <div className="space-y-1 text-left">
      <p className="text-blue-400">import <span className="text-white">React</span> from <span className="text-green-400">&apos;react&apos;</span>;</p>
      <p className="text-blue-400">export default function <span className="text-purple-400">App</span>() &#123;</p>
      <p className="pl-2 text-zinc-500">{"// Generated by Xcelerate Swarm"}</p>
      <p className="pl-2 text-blue-400">return (</p>
      <p className="pl-4 text-purple-400">&lt;<span className="text-blue-400">div</span> className=<span className="text-green-400">&quot;bg-black text-white&quot;</span>&gt;</p>
      <p className="pl-6 text-purple-400">&lt;<span className="text-blue-400">h1</span>&gt;Velocity SaaS&lt;/<span className="text-blue-400">h1</span>&gt;</p>
      <p className="pl-4 text-purple-400">&lt;/<span className="text-blue-400">div</span>&gt;</p>
      <p className="pl-2 text-blue-400">);</p>
      <p className="text-blue-400">&#125;</p>
    </div>
    <div className="absolute bottom-1.5 right-1.5 opacity-30">
      <RobotAgent agentId="product" size={60} typing={true} />
    </div>
  </div>
);

const FinanceVisual = () => (
  <div className="w-full h-24 flex items-end justify-between px-2 pt-6 select-none relative overflow-hidden bg-black/40 border border-white/5 rounded-xl">
    <div className="absolute inset-0 bg-gradient-to-t from-blue-500/5 to-transparent z-0" />
    <svg className="w-full h-full overflow-visible z-10" viewBox="0 0 100 40">
      <defs>
        <linearGradient id="chart-glow" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#3B82F6" stopOpacity="0.4" />
          <stop offset="100%" stopColor="#3B82F6" stopOpacity="0.0" />
        </linearGradient>
      </defs>
      <path
        d="M 0,40 Q 20,35 40,25 T 80,12 T 100,2 L 100,40 L 0,40 Z"
        fill="url(#chart-glow)"
      />
      <path
        d="M 0,40 Q 20,35 40,25 T 80,12 T 100,2"
        fill="none"
        stroke="#3B82F6"
        strokeWidth="2"
      />
      <circle cx="40" cy="25" r="1.5" fill="#FFFFFF" />
      <circle cx="80" cy="12" r="1.5" fill="#FFFFFF" />
      <circle cx="100" cy="2" r="2" fill="#3B82F6" className="animate-pulse" />
    </svg>
  </div>
);

const SwarmVisual = () => (
  <div className="w-full h-24 flex items-center justify-center gap-2 relative overflow-hidden select-none bg-black/40 border border-white/5 rounded-xl">
    <div className="absolute inset-0 flex items-center justify-center opacity-25">
      <svg className="w-full h-full overflow-visible" viewBox="0 0 200 80">
        <path d="M 30,40 L 80,40 M 80,40 L 120,40 M 120,40 L 170,40 M 80,40 L 100,15 L 120,40 M 80,40 L 100,65 L 120,40" stroke="#FFFFFF" strokeWidth="1" strokeDasharray="3 3" />
      </svg>
    </div>
    <div className="flex gap-2.5 z-10">
      {["ceo", "product", "growth", "operations"].map((id) => (
        <div key={id} className="w-7 h-7 rounded bg-white/5 border border-white/10 flex items-center justify-center overflow-hidden">
          <RobotAgent agentId={id} size={24} headOnly={true} />
        </div>
      ))}
    </div>
  </div>
);

const GtmVisual = () => (
  <div className="w-full h-full min-h-[140px] bg-black/60 rounded-xl border border-white/5 p-4 flex flex-col justify-between shadow-2xl select-none relative overflow-hidden">
    <div className="space-y-2">
      <div className="flex justify-between items-center text-[10px]">
        <span className="text-zinc-500 font-medium">Outreach Funnel</span>
        <span className="text-green-400 font-bold">+14.2%</span>
      </div>
      <div className="space-y-1.5 text-left">
        {[
          { label: "Target Creators", width: "90%", color: "bg-blue-500/80" },
          { label: "Sent Sequenced DMs", width: "70%", color: "bg-purple-500/80" },
          { label: "Acquired Leads", width: "45%", color: "bg-pink-500/80" }
        ].map((bar, i) => (
          <div key={i} className="space-y-0.5">
            <div className="flex justify-between text-[8px] text-zinc-400">
              <span>{bar.label}</span>
              <span>{bar.width}</span>
            </div>
            <div className="h-1 bg-white/5 rounded-full overflow-hidden">
              <div 
                className={`h-full ${bar.color} rounded-full`}
                style={{ width: bar.width }}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
    <div className="flex gap-1.5 mt-2">
      {["SEO", "Soc", "Ads"].map((tag) => (
        <span key={tag} className="text-[8px] font-mono text-zinc-400 px-1.5 py-0.5 rounded border border-white/5 bg-white/5">{tag}</span>
      ))}
    </div>
  </div>
);

interface BentoCardProps {
  id: string;
  title: string;
  desc: string;
  icon: React.ElementType;
  span?: number;
}

function BentoCard({ id, title, desc, icon: Icon, span = 1 }: BentoCardProps) {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [isHovered, setIsHovered] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    setMousePosition({ x: e.clientX - rect.left, y: e.clientY - rect.top });
  };

  const renderVisual = () => {
    switch (id) {
      case "code":
        return <CodeVisual />;
      case "finance":
        return <FinanceVisual />;
      case "swarm":
        return <SwarmVisual />;
      case "gtm":
        return <GtmVisual />;
      default:
        return null;
    }
  };

  return (
    <div
      ref={cardRef}
      onMouseMove={handleMouseMove}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className={`rounded-2xl glass-panel relative overflow-hidden group border border-white/5 transition-all duration-300 ${span === 2 ? 'md:col-span-2' : ''}`}
    >
      <style>{`
        @keyframes border-gradient-move {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        .bento-card-glow {
          position: absolute;
          inset: 0;
          z-index: 0;
          opacity: 0;
          transition: opacity 0.4s ease;
          background: linear-gradient(135deg, rgba(59,130,246,0.08) 0%, rgba(168,85,247,0.08) 50%, rgba(236,72,153,0.08) 100%);
          background-size: 200% 200%;
          animation: border-gradient-move 6s ease infinite;
        }
        .group:hover .bento-card-glow {
          opacity: 1;
        }
        .bento-card-border {
          position: absolute;
          inset: 0;
          border-radius: 1rem;
          padding: 1px;
          background: transparent;
          transition: background 0.3s ease;
          pointer-events: none;
          z-index: 1;
          -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          -webkit-mask-composite: xor;
          mask-composite: exclude;
        }
        .group:hover .bento-card-border {
          background: linear-gradient(135deg, #3B82F6, #A855F7, #EC4899);
          background-size: 200% 200%;
          animation: border-gradient-move 4s linear infinite;
        }
      `}</style>

      {/* Moving border gradient */}
      <div className="bento-card-border" />

      {/* Moving background gradient */}
      <div className="bento-card-glow" />

      <div 
        className="absolute inset-0 z-0 transition-opacity duration-300 pointer-events-none"
        style={{
          background: isHovered 
            ? `radial-gradient(400px circle at ${mousePosition.x}px ${mousePosition.y}px, rgba(255,255,255,0.06), transparent 40%)` 
            : 'transparent'
        }}
      />
      
      {/* Card Content Layout */}
      <div className="relative z-10 p-8 h-full flex flex-col justify-between text-left">
        {span === 2 ? (
          // Side Design Layout for wide cards
          <div className="flex flex-col md:flex-row gap-6 items-stretch justify-between h-full">
            <div className="flex-1 flex flex-col justify-center">
              <div className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center mb-6 border border-white/10 group-hover:bg-white/10 transition-colors">
                <Icon className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-2xl font-bold mb-3 tracking-tight">{title}</h3>
              <p className="text-zinc-400 leading-relaxed text-sm md:text-base">{desc}</p>
            </div>
            <div className="flex-1 flex items-center justify-center min-w-[200px] md:max-w-[320px]">
              {renderVisual()}
            </div>
          </div>
        ) : (
          // Top-to-Bottom Layout for narrow cards
          <div className="flex flex-col gap-6 h-full justify-between">
            <div>
              <div className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center mb-6 border border-white/10 group-hover:bg-white/10 transition-colors">
                <Icon className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-2xl font-bold mb-3 tracking-tight">{title}</h3>
              <p className="text-zinc-400 leading-relaxed text-sm md:text-base">{desc}</p>
            </div>
            <div className="mt-4">
              {renderVisual()}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

const MvpSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 font-mono text-[9px] text-zinc-500 justify-between select-none bg-black/40">
    <div className="flex items-center justify-between border-b border-white/5 pb-2">
      <span className="text-[8px] text-blue-400">api/auth/route.ts</span>
      <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
    </div>
    <div className="space-y-1 mt-1 text-left flex-1">
      <p className="text-zinc-400"><span className="text-purple-400">export async function</span> POST(req: Request) &#123;</p>
      <p className="pl-3 text-zinc-400">const body = <span className="text-blue-400">await</span> req.json();</p>
      <p className="pl-3 text-zinc-400">const user = <span className="text-blue-400">await</span> db.user.create(&#123; data: body &#125;);</p>
      <p className="pl-3 text-zinc-400">return NextResponse.json(&#123; user &#125;);</p>
      <p className="text-zinc-400">&#125;</p>
    </div>
    <div className="flex justify-between items-center text-[7px] border-t border-white/5 pt-2">
      <span className="text-zinc-500">Database connected</span>
      <span className="text-green-500">✓ Ready</span>
    </div>
  </div>
);

const PitchDeckSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 justify-between bg-zinc-950 select-none relative overflow-hidden text-left">
    <div className="absolute top-0 right-0 w-16 h-16 bg-blue-500/10 rounded-full blur-xl" />
    <div className="space-y-1">
      <span className="text-[8px] font-mono text-zinc-600 tracking-widest uppercase">Slide 04 / Market Size</span>
      <h4 className="text-xs font-bold text-white tracking-tight leading-tight mt-0.5">Addressing the $12B TAM</h4>
    </div>
    
    <div className="grid grid-cols-3 gap-2 mt-2 flex-1 items-end">
      <div className="space-y-1">
        <div className="h-10 bg-white/5 border border-white/10 rounded flex items-center justify-center text-[9px] font-bold text-zinc-300">SOM</div>
        <p className="text-[7px] text-zinc-500 text-center">$1.2B</p>
      </div>
      <div className="space-y-1">
        <div className="h-14 bg-blue-500/10 border border-blue-500/20 rounded flex items-center justify-center text-[9px] font-bold text-blue-400">SAM</div>
        <p className="text-[7px] text-blue-400 text-center">$4.5B</p>
      </div>
      <div className="space-y-1">
        <div className="h-16 bg-purple-500/10 border border-purple-500/20 rounded flex items-center justify-center text-[9px] font-bold text-purple-400">TAM</div>
        <p className="text-[7px] text-purple-400 text-center">$12B</p>
      </div>
    </div>
  </div>
);

const GtmSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-3 justify-between bg-black/40 select-none relative overflow-hidden text-left">
    <div className="flex items-center gap-2 mb-1.5">
      <div className="w-5 h-5 rounded-full bg-zinc-800 border border-white/10 flex items-center justify-center text-[9px] font-bold text-white">M</div>
      <div className="flex flex-col">
        <span className="text-[9px] font-bold text-white leading-tight">maya_growth</span>
        <span className="text-[7px] text-zinc-500">Instagram Reels campaign</span>
      </div>
    </div>
    
    <div className="flex-1 bg-zinc-900/60 rounded border border-white/5 p-2 flex flex-col justify-between">
      <p className="text-[9px] text-zinc-300 font-semibold leading-snug">&ldquo;POV: You build a whole SaaS with one command.&rdquo;</p>
      <div className="flex items-center justify-between text-[7px] text-zinc-500 mt-2">
        <span>Target Hook: <strong>92% Engagement</strong></span>
        <span className="text-zinc-400">14k views</span>
      </div>
    </div>
    
    <div className="flex justify-between items-center mt-1.5 text-[8px] text-zinc-500">
      <span>CTR: <strong className="text-green-400">4.8%</strong></span>
      <span>RoAS: <strong className="text-blue-400">3.5x</strong></span>
    </div>
  </div>
);

const BrandSkillVisual = () => (
  <div className="w-full h-full flex flex-col p-4 justify-between bg-zinc-950 select-none text-left">
    <div className="flex justify-between items-start">
      <div className="space-y-1">
        <span className="text-[8px] font-mono text-zinc-600 tracking-wider">Style System</span>
        <h4 className="text-xs font-bold text-white">Aa <span className="font-light text-zinc-400">Outfit Bold</span></h4>
      </div>
      <div className="flex gap-1">
        {["#000000", "#3B82F6", "#A855F7"].map((hex) => (
          <div key={hex} className="flex flex-col items-center gap-0.5">
            <div className="w-4 h-4 rounded-full border border-white/10" style={{ background: hex }} />
            <span className="text-[6px] font-mono text-zinc-500">{hex}</span>
          </div>
        ))}
      </div>
    </div>
    
    <div className="h-12 border border-dashed border-white/10 rounded flex items-center justify-center relative overflow-hidden bg-black/40">
      <svg className="w-16 h-16 text-white/10 absolute -rotate-12" viewBox="0 0 100 100">
        <path d="M 50,10 L 90,90 L 10,90 Z" fill="none" stroke="currentColor" strokeWidth="2" />
      </svg>
      <div className="flex items-center gap-1.5 z-10">
        <div className="w-5 h-5 rounded bg-white flex items-center justify-center">
          <span className="text-[10px] font-bold text-black">X</span>
        </div>
        <span className="text-[10px] font-bold text-white tracking-widest uppercase">Xcelerate</span>
      </div>
    </div>
  </div>
);

interface SkillCardProps {
  id: string;
  title: string;
  desc: string;
  tag: string;
  apps: string[];
}

function SkillCard({ id, title, desc, tag, apps }: SkillCardProps) {
  const renderVisual = () => {
    switch (id) {
      case "mvp":
        return <MvpSkillVisual />;
      case "deck":
        return <PitchDeckSkillVisual />;
      case "gtm":
        return <GtmSkillVisual />;
      case "brand":
        return <BrandSkillVisual />;
      default:
        return null;
    }
  };

  return (
    <div className="flex-none w-[320px] md:w-[380px] flex flex-col gap-4 scroll-snap-align-start group/card cursor-pointer">
      <div className="bg-[#0A0A0A] border border-white/5 rounded-2xl p-2 h-[220px] flex flex-col relative overflow-hidden transition-all duration-300 group-hover/card:border-white/20 group-hover/card:bg-[#0f0f0f]">
        {/* Top bar simulating browser/app */}
        <div className="flex items-center gap-2 mb-2 p-2">
           <div className="flex gap-1.5">
             <div className="w-2.5 h-2.5 rounded-full bg-white/10"></div>
             <div className="w-2.5 h-2.5 rounded-full bg-white/10"></div>
             <div className="w-2.5 h-2.5 rounded-full bg-white/10"></div>
           </div>
           <div className="ml-2 px-3 py-1 rounded-full bg-white/5 text-[10px] font-mono text-zinc-400 font-medium group-hover/card:bg-white/10 group-hover/card:text-zinc-200 transition-colors">
             {tag}
           </div>
        </div>
        {/* Content area */}
        <div className="flex-1 bg-black/50 rounded-xl border border-white/5 relative overflow-hidden flex flex-col m-2 mt-0 transition-colors group-hover/card:bg-black/80">
            {renderVisual()}
        </div>
      </div>
      <div className="px-1 text-left">
        <h3 className="text-xl font-bold mb-2 text-white">{title}</h3>
        <p className="text-zinc-400 text-sm leading-relaxed mb-4">{desc}</p>
        <div className="flex gap-2 items-center">
           {apps.map((app: string, i: number) => (
             <div key={i} className="w-6 h-6 rounded-md bg-white/5 border border-white/10 flex items-center justify-center text-[10px] font-bold text-zinc-400 shadow-sm transition-all group-hover/card:border-white/20 group-hover/card:text-zinc-300">
               {app}
             </div>
           ))}
        </div>
      </div>
    </div>
  );
}

function HowItHelpsSection() {
  const scrollRef = useRef<HTMLDivElement>(null);

  const scroll = (direction: 'left' | 'right') => {
    if (scrollRef.current) {
      const { current } = scrollRef;
      const scrollAmount = direction === 'left' ? -400 : 400;
      current.scrollBy({ left: scrollAmount, behavior: 'smooth' });
    }
  };

  return (
    <section className="relative z-10 py-24 px-6 max-w-7xl mx-auto border-t border-white/5">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
        <div className="max-w-2xl">
          <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">How Xcelerate can help you</h2>
          <p className="text-zinc-400 text-lg">Explore specialized capabilities designed to help every founder build, launch, and scale their ideas faster than ever before.</p>
        </div>
        <div className="flex gap-3">
          <button onClick={() => scroll('left')} className="w-10 h-10 rounded-full border border-white/10 flex items-center justify-center text-zinc-400 hover:text-white hover:bg-white/5 transition-all">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <button onClick={() => scroll('right')} className="w-10 h-10 rounded-full border border-white/10 flex items-center justify-center text-zinc-400 hover:text-white hover:bg-white/5 transition-all">
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div 
        ref={scrollRef}
        className="flex gap-6 overflow-x-auto pb-8 snap-x snap-mandatory hide-scrollbar -mx-6 px-6"
      >
        <SkillCard 
          id="mvp"
          tag="/build-mvp"
          title="Build an MVP"
          desc="Generate a complete, deployable Next.js application with authentication, database schemas, and API routes in minutes."
          apps={["Nx", "DB", "Api", "Ts"]}
        />
        <SkillCard 
          id="deck"
          tag="/write-pitch-deck"
          title="Write a Pitch Deck"
          desc="Create a compelling narrative with automated financial projections, market sizing, and competitor analysis."
          apps={["Doc", "Xls", "Pdf"]}
        />
        <SkillCard 
          id="gtm"
          tag="/launch-campaign"
          title="Launch Go-To-Market"
          desc="Generate targeted SEO content, social media clusters, and personalized outreach sequences for early adopters."
          apps={["SEO", "Soc", "Ads"]}
        />
        <SkillCard 
          id="brand"
          tag="/design-brand"
          title="Design Brand Identity"
          desc="Create logos, color palettes, typography systems, and brand guidelines that feel premium and modern."
          apps={["Fig", "Svg", "Css"]}
        />
      </div>
    </section>
  );
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.3,
    }
  }
};

const robotVariants = {
  hidden: { 
    opacity: 0, 
    scale: 0.3, 
    y: 40,
    filter: "blur(8px)" 
  },
  visible: { 
    opacity: 1, 
    scale: 1, 
    y: 0,
    filter: "blur(0px)",
    transition: {
      type: "spring" as const,
      stiffness: 100,
      damping: 15
    }
  }
};

export default function LandingPage() {
  const router = useRouter();
  const [idea, setIdea] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [placeholderIndex, setPlaceholderIndex] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [theme, setTheme] = useState<"light" | "dark">("dark");

  useEffect(() => {
    const savedTheme = (localStorage.getItem("theme") as "light" | "dark") || "dark";
    setTheme(savedTheme);
    if (savedTheme === "light") {
      document.documentElement.classList.add("light");
    } else {
      document.documentElement.classList.remove("light");
    }
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === "dark" ? "light" : "dark";
    setTheme(newTheme);
    localStorage.setItem("theme", newTheme);
    if (newTheme === "light") {
      document.documentElement.classList.add("light");
    } else {
      document.documentElement.classList.remove("light");
    }
  };
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isTyping) return;
    const interval = setInterval(() => {
      setPlaceholderIndex((i) => (i + 1) % PLACEHOLDERS.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [isTyping]);

  const handleSubmit = (e?: React.FormEvent) => {
    e?.preventDefault();
    if (!idea.trim() || isSubmitting) return;
    setIsSubmitting(true);
    const id = generateId();
    sessionStorage.setItem("xcelerate_idea", idea.trim());
    sessionStorage.setItem("xcelerate_project_id", id);
    router.push(`/workspace/${id}/build`);
  };

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden font-sans">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-dot-pattern opacity-40 z-0"></div>
      <div className="glow-bg z-0"></div>
      <Meteors number={15} />

      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-[var(--border)] bg-[var(--background)]/75 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => router.push("/")}>
            <div className="w-8 h-8 rounded bg-[var(--foreground)] flex items-center justify-center">
              <Zap className="w-4 h-4 text-[var(--background)] fill-[var(--background)]" />
            </div>
            <span className="font-bold text-lg tracking-tight text-[var(--foreground)]">Xcelerate</span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-[var(--muted)]">
            <a href="#features" className="hover:text-[var(--foreground)] transition-colors">Features</a>
            <a href="#agents" className="hover:text-[var(--foreground)] transition-colors">AI Swarm</a>
            <a href="#pricing" className="hover:text-[var(--foreground)] transition-colors">Pricing</a>
          </div>
          <div className="flex items-center gap-4">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-full border border-[var(--border)] bg-[var(--surface)] hover:bg-[var(--border)] transition-all text-[var(--muted)] hover:text-[var(--foreground)] flex items-center justify-center shadow-sm"
              aria-label="Toggle Theme"
            >
              {theme === "dark" ? (
                <Sun className="w-4 h-4 text-yellow-400" />
              ) : (
                <Moon className="w-4 h-4 text-blue-500" />
              )}
            </button>
            <button
              onClick={() => router.push("/demo")}
              className="text-sm font-medium text-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
            >
              Live Demo
            </button>
            <button
              onClick={() => inputRef.current?.focus()}
              className="px-4 py-2 rounded-full text-sm font-bold bg-[var(--foreground)] text-[var(--background)] hover:opacity-90 transition-all shadow-sm"
            >
              Start Building
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="relative z-10 pt-44 pb-20 px-6 max-w-5xl mx-auto text-center flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="w-full flex flex-col items-center"
        >
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/10 bg-white/5 text-xs text-zinc-300 mb-8 backdrop-blur-md shadow-2xl">
            <Sparkles className="w-3.5 h-3.5 text-blue-400" />
            <span className="font-medium">Xcelerate Swarm v3.4 is live</span>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse ml-1" />
          </div>

          {/* Swarm Cinematic Lineup */}
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="flex justify-center items-center gap-6 md:gap-10 mb-8 mt-2"
          >
            {[
              { id: "ceo", name: "Nova", role: "CEO", yOffset: [-4, 4] },
              { id: "product", name: "Mira", role: "Product", yOffset: [-6, 2] },
              { id: "growth", name: "Ari", role: "Growth", yOffset: [-3, 5] },
              { id: "operations", name: "Noah", role: "Operations", yOffset: [-5, 3] }
            ].map((bot, idx) => (
              <motion.div
                key={bot.id}
                variants={robotVariants}
                animate={{
                  y: bot.yOffset,
                  transition: {
                    duration: 2 + idx * 0.3,
                    repeat: Infinity,
                    repeatType: "reverse",
                    ease: "easeInOut"
                  }
                }}
                className="flex flex-col items-center relative group"
              >
                {/* Floating glow behind robot */}
                <div className="absolute -inset-1 bg-gradient-to-b from-blue-500/10 to-purple-500/10 rounded-full blur-md opacity-0 group-hover:opacity-100 transition duration-500" />
                <RobotAgent agentId={bot.id} size={90} typing={true} />
                <span className="text-[10px] font-bold text-zinc-500 mt-2 px-2 py-0.5 rounded-full border border-white/5 bg-white/5 uppercase tracking-wider group-hover:text-white group-hover:border-white/10 transition-colors">
                  {bot.role}
                </span>
              </motion.div>
            ))}
          </motion.div>

          {/* Headline */}
          <h1 className="text-5xl md:text-7xl lg:text-[5rem] font-extrabold tracking-tight mb-8 leading-[1.1] max-w-4xl">
            Build an entire company.<br />
            <span className="text-gradient">With a single prompt.</span>
          </h1>

          {/* Subtitle */}
          <p className="text-lg md:text-xl text-zinc-400 max-w-2xl mx-auto mb-12 leading-relaxed font-medium">
            Xcelerate deploys specialized AI Directors—Product, Engineering, Growth, and Finance—to build your startup in parallel.
          </p>

          {/* Hero Input (The Command Bar) */}
          <div className="w-full max-w-3xl mx-auto relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-blue-500 to-purple-600 rounded-2xl blur-md opacity-20 group-focus-within:opacity-60 transition duration-1000 group-hover:opacity-60"></div>
            <form
              onSubmit={handleSubmit}
              className="relative flex items-center bg-[#050505] border border-white/10 rounded-2xl p-2 shadow-2xl transition-all duration-300 hover:border-white/20 focus-within:border-white/30"
            >
              <div className="pl-4 pr-2">
                <Terminal className="w-5 h-5 text-zinc-400" />
              </div>
              <div className="relative w-full h-14 flex items-center">
                <input
                  ref={inputRef}
                  type="text"
                  value={idea}
                  onChange={(e) => {
                    setIdea(e.target.value);
                    setIsTyping(e.target.value.length > 0);
                  }}
                  onFocus={() => setIsTyping(true)}
                  onBlur={() => setIsTyping(idea.length > 0)}
                  className="w-full h-full bg-transparent text-white text-lg font-medium outline-none placeholder:text-transparent"
                  placeholder=""
                />
                {!idea && (
                  <div className="absolute inset-0 flex items-center pointer-events-none text-zinc-500 text-lg font-medium">
                    <AnimatePresence mode="wait">
                      <motion.span
                        key={placeholderIndex}
                        initial={{ opacity: 0, y: 4 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -4 }}
                        transition={{ duration: 0.2 }}
                      >
                        {PLACEHOLDERS[placeholderIndex]}
                      </motion.span>
                    </AnimatePresence>
                  </div>
                )}
              </div>
              <button
                type="submit"
                disabled={!idea.trim() || isSubmitting}
                className="ml-2 mr-1 px-8 h-12 rounded-xl bg-white text-black font-bold hover:bg-zinc-200 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
              >
                {isSubmitting ? (
                  <div className="w-4 h-4 border-2 border-black/20 border-t-black rounded-full animate-spin" />
                ) : (
                  <>
                    Build <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Quick links */}
          <div className="mt-8 flex items-center gap-4 text-sm text-zinc-500 font-medium">
            <span>Press <kbd className="px-1.5 py-0.5 rounded bg-white/10 text-zinc-300 font-mono text-xs mx-1 border border-white/10">Enter</kbd> to execute</span>
            <span>•</span>
            <button onClick={() => { setIdea(PLACEHOLDERS[0]); setIsTyping(true); }} className="hover:text-zinc-300 transition-colors">Try an example</button>
          </div>
        </motion.div>
      </main>

      {/* Trusted By Banner */}
      <section className="relative z-10 border-y border-white/5 bg-white/[0.01] py-8 overflow-hidden mb-24">
        <div className="max-w-7xl mx-auto px-6 flex flex-col items-center">
          <p className="text-xs uppercase tracking-widest text-zinc-500 font-bold mb-6 flex items-center gap-2">
            <ShieldCheck className="w-4 h-4" /> Trusted by 10,000+ AI Native Founders
          </p>
          <div className="flex gap-12 text-zinc-600 font-bold text-xl md:text-2xl filter grayscale opacity-50 justify-center flex-wrap">
            <span>Stripe</span>
            <span>Vercel</span>
            <span>Supabase</span>
            <span>Shopify</span>
            <span>Linear</span>
          </div>
        </div>
      </section>

      {/* Hero Visual Mockup */}
      <section className="relative z-10 px-6 max-w-6xl mx-auto pb-32">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.2 }}
          className="rounded-2xl border border-white/10 bg-[#050505] shadow-[0_0_100px_-20px_rgba(59,130,246,0.3)] overflow-hidden animate-float"
        >
          {/* Window Header */}
          <div className="h-12 border-b border-white/5 flex items-center px-4 gap-2 bg-[#0A0A0A]">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
              <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
            </div>
            <div className="mx-auto px-4 py-1.5 rounded-md bg-white/5 text-xs text-zinc-400 font-mono flex items-center gap-2 shadow-inner border border-white/5">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              xcelerate-workspace.app
            </div>
          </div>
          {/* Window Body */}
          <div className="aspect-[16/9] w-full bg-[#000000] p-6 relative overflow-hidden flex flex-col md:flex-row gap-6">
             <div className="flex-1 border border-white/5 rounded-xl bg-[#0A0A0A] p-5 flex flex-col shadow-inner">
                <div className="text-xs text-zinc-500 font-mono mb-4 border-b border-white/5 pb-2">Terminal Feed</div>
                <div className="space-y-4 font-mono text-[11px] text-zinc-400">
                  <div className="flex gap-2"><span className="text-blue-400">[Product]</span> Generating PRD for AI Video Editor...</div>
                  <div className="flex gap-2"><span className="text-green-400">[Engineering]</span> Bootstrapping Next.js 15 repository...</div>
                  <div className="flex gap-2"><span className="text-purple-400">[Growth]</span> Mapping 100-creator outreach pipeline...</div>
                  <div className="flex gap-2"><span className="text-yellow-400">[Finance]</span> Calculating AWS compute unit margins...</div>
                </div>
             </div>
             <div className="flex-[2] border border-white/5 rounded-xl bg-[#0A0A0A] p-6 flex flex-col items-center justify-center relative overflow-hidden shadow-inner min-h-[300px]">
                <div className="absolute top-4 left-4 text-xs font-bold text-zinc-500 uppercase tracking-widest flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                  <span>Swarm Live Collaboration</span>
                </div>
                
                <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
                  {[
                    { id: "ceo", name: "Nova", role: "AI CEO" },
                    { id: "product", name: "Mira", role: "Product" },
                    { id: "growth", name: "Ari", role: "Growth" },
                    { id: "operations", name: "Noah", role: "Operations" }
                  ].map((bot) => (
                    <div key={bot.id} className="flex flex-col items-center p-3 rounded-xl border border-white/5 bg-black/40 hover:border-white/10 transition-colors">
                      <RobotAgent agentId={bot.id} size={80} typing={true} />
                      <div className="text-center mt-2">
                        <p className="text-[11px] font-bold text-white leading-none">{bot.name}</p>
                        <p className="text-[9px] text-zinc-400 mt-1 uppercase tracking-wider">{bot.role}</p>
                      </div>
                    </div>
                  ))}
                </div>
             </div>
          </div>
        </motion.div>
      </section>

      {/* How It Helps Section */}
      <HowItHelpsSection />

      {/* Feature Bento Grid */}
      <section id="features" className="relative z-10 py-24 px-6 max-w-6xl mx-auto border-t border-white/5">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4 text-gradient">The autonomous architecture.</h2>
          <p className="text-zinc-400 text-lg font-medium">Built for founders who want to move at the speed of thought.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <BentoCard 
            id="code"
            title="Production Code Generation" 
            desc="Not just mockups. Xcelerate writes complete Next.js 15 applications with Tailwind CSS, Supabase databases, and fully typed APIs. Ready to deploy to Vercel with one click." 
            icon={Code2} 
            span={2} 
          />
          <BentoCard 
            id="finance"
            title="Financial Modeling" 
            desc="Instant 5-year unit economics, MRR projections, and cap table generation for your pitch deck." 
            icon={LineChart} 
          />
          <BentoCard 
            id="swarm"
            title="Parallel Agents" 
            desc="4 specialized agents work simultaneously, debating trade-offs and building your startup 4x faster." 
            icon={Boxes} 
          />
          <BentoCard 
            id="gtm"
            title="Go-To-Market Automation" 
            desc="Generate 30-day launch roadmaps, programmatic SEO clusters, and personalized creator outreach DMs instantly." 
            icon={Briefcase} 
            span={2} 
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="relative z-10 py-32 px-6 max-w-4xl mx-auto text-center border-t border-white/5">
         <h2 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">Stop planning. Start building.</h2>
         <p className="text-zinc-400 text-lg mb-8">Join thousands of founders launching their next big idea with Xcelerate.</p>
         <button 
           onClick={() => {
             window.scrollTo({ top: 0, behavior: "smooth" });
             setTimeout(() => inputRef.current?.focus(), 800);
           }}
           className="px-8 py-4 rounded-full text-lg font-bold bg-white text-black hover:bg-zinc-200 transition-all shadow-[0_0_40px_-10px_rgba(255,255,255,0.5)]"
         >
           Create your company now
         </button>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-12 px-6 bg-black">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <Zap className="w-5 h-5 text-white fill-white" />
            <span className="font-bold tracking-tight">Xcelerate</span>
          </div>
          <div className="flex items-center gap-6 text-sm text-zinc-500 font-medium">
            <span>© {new Date().getFullYear()} Xcelerate Inc.</span>
            <a href="#" className="hover:text-white transition-colors">Twitter</a>
            <a href="#" className="hover:text-white transition-colors">GitHub</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
