// ─────────────────────────────────────────────────────────────────
// ACCELERATE AI — Demo Data (Velocity Project)
// Pre-populated sneaker brand project for demo mode
// ─────────────────────────────────────────────────────────────────

import type {
  Project,
  BrandArtifact,
  ProductArtifact,
  GrowthArtifact,
  OperationsArtifact,
  Task,
  Decision,
  ActivityItem,
  ContentIdea,
  Trend,
  Creator,
} from "@/lib/types";

export const DEMO_PROJECT: Project = {
  id: "velocity-demo",
  name: "Velocity",
  tagline: "Premium Running Footwear",
  idea: "I want to build a premium sneaker ecommerce brand for Gen Z",
  stage: "BUILDING",
  readiness: 86,
  createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
};

export const DEMO_BRAND: BrandArtifact = {
  name: "Velocity",
  tagline: "Run your way.",
  positioning: "Premium minimalist running footwear for Gen Z urban runners who want style and performance without compromise.",
  personality: ["Minimal", "Confident", "Energetic", "Modern", "Authentic"],
  colors: {
    primary: "#0B0B0C",
    secondary: "#F7F6F2",
    accent: "#E63946",
    background: "#FAFAF8",
  },
  typography: {
    display: "Clash Display",
    body: "Inter",
  },
  voice: [
    "Speak like a friend, not a brand",
    "Short sentences. Real words.",
    "Performance with personality",
    "Never corporate, always human",
  ],
  targetCustomer: "Gen Z urban runners aged 18–28 who follow sneaker culture, value aesthetics, and want running shoes that don't look like running shoes.",
  status: "APPROVED",
};

export const DEMO_PRODUCT: ProductArtifact = {
  definition: "Velocity is a premium DTC running footwear brand built for Gen Z urban athletes who refuse to choose between style and performance.",
  targetUser: "Urban Gen Z runners (18–28) in metro cities who follow sneaker culture and want premium-looking performance footwear.",
  problem: "Running shoes are either high-performance-but-ugly or stylish-but-uncomfortable. Gen Z wants both.",
  valueProp: "The only running shoe that you'd wear to the gym, the street, and a coffee shop — and still perform in.",
  differentiation: "Premium materials, minimal design language, aggressive DTC pricing, culture-first marketing.",
  mvpFeatures: [
    "Product catalog (3 colorways)",
    "Product detail page",
    "Cart & checkout",
    "Size guide",
    "Reviews system",
  ],
  v2Features: [
    "Loyalty program",
    "Personalization engine",
    "Referral system",
    "Community forum",
    "Custom colorway builder",
  ],
  status: "APPROVED",
};

export const DEMO_CONTENT_IDEAS: ContentIdea[] = [
  {
    id: "c1",
    title: "POV: You found running shoes that don't look like running shoes",
    hook: "POV: You finally found running shoes that don't look like running shoes.",
    format: "Reel",
    platform: "Instagram",
    funnelStage: "Awareness",
    cta: "Link in bio",
    status: "READY",
  },
  {
    id: "c2",
    title: "Rating every Gen Z running shoe (honest review)",
    hook: "I rated every 'Gen Z running shoe' so you don't have to.",
    format: "Carousel",
    platform: "Instagram",
    funnelStage: "Consideration",
    cta: "Save this post",
    status: "READY",
  },
  {
    id: "c3",
    title: "My morning run fit check",
    hook: "The fit check that got me 3 compliments on a Tuesday morning run.",
    format: "Reel",
    platform: "Instagram",
    funnelStage: "Awareness",
    cta: "Comment your city",
    status: "IDEA",
  },
  {
    id: "c4",
    title: "Founder's first 100 customers story",
    hook: "How we found our first 100 customers without paid ads.",
    format: "Founder",
    platform: "YouTube",
    funnelStage: "Awareness",
    cta: "Subscribe",
    status: "IN_PROGRESS",
  },
  {
    id: "c5",
    title: "Street interview: Rate these running fits",
    hook: "We asked 50 people on the street to rate these running fits.",
    format: "UGC",
    platform: "Instagram",
    funnelStage: "Awareness",
    cta: "Drop your rating",
    status: "IDEA",
  },
  {
    id: "c6",
    title: "Why running shoes are ruining your style",
    hook: "This is why your running shoes are ruining your entire fit.",
    format: "Educational",
    platform: "Instagram",
    funnelStage: "Consideration",
    cta: "Swipe to see the alternative",
    status: "READY",
  },
];

export const DEMO_TRENDS: Trend[] = [
  {
    id: "t1",
    name: "Street interview format",
    platform: "Instagram / TikTok",
    momentum: "HIGH",
    brandFit: 92,
    risk: "LOW",
    category: "TRENDING",
    adaptation: "Rate these running fits — ask people on the street to rate different sneakers on style/performance",
  },
  {
    id: "t2",
    name: "Founder storytelling",
    platform: "YouTube / Instagram",
    momentum: "HIGH",
    brandFit: 88,
    risk: "LOW",
    category: "EVERGREEN",
    adaptation: "Document the Velocity build journey — first factory visit, first sample, first sale",
  },
  {
    id: "t3",
    name: "Morning routine reels",
    platform: "Instagram",
    momentum: "MEDIUM",
    brandFit: 85,
    risk: "LOW",
    category: "EMERGING",
    adaptation: "Morning run aesthetics — fog, early city, Velocity shoes",
  },
  {
    id: "t4",
    name: "POV format",
    platform: "Instagram / TikTok",
    momentum: "HIGH",
    brandFit: 90,
    risk: "LOW",
    category: "TRENDING",
    adaptation: "POV: You found the running shoe that goes with every fit",
  },
  {
    id: "t5",
    name: "AI-generated content",
    platform: "All",
    momentum: "HIGH",
    brandFit: 45,
    risk: "HIGH",
    category: "NOT_RECOMMENDED",
    adaptation: "Not recommended — Velocity is human-first brand. Use UGC instead.",
  },
];

export const DEMO_CREATORS: Creator[] = [
  {
    id: "cr1",
    name: "Arjun Mehta",
    handle: "@arjunruns",
    platform: "Instagram",
    category: "Running / Fitness",
    audience: 280000,
    engagement: 4.2,
    estimatedCost: 35000,
    brandFit: 94,
    status: "SHORTLISTED",
    whyFit: "Authentic runner, strong Gen Z audience in metro cities, natural storyteller",
    campaignIdea: "Week with Velocity — 7-day running challenge in Velocity shoes",
  },
  {
    id: "cr2",
    name: "Sneha Kapoor",
    handle: "@snehastyle",
    platform: "Instagram",
    category: "Fashion / Streetwear",
    audience: 145000,
    engagement: 6.8,
    estimatedCost: 22000,
    brandFit: 89,
    status: "IDENTIFIED",
    whyFit: "High engagement, fashion-forward audience that overlaps with sneaker culture",
    campaignIdea: "Styling Velocity — 5 outfit combinations featuring the shoes",
  },
  {
    id: "cr3",
    name: "Rohan Desai",
    handle: "@rohanfit",
    platform: "YouTube",
    category: "Fitness / Lifestyle",
    audience: 890000,
    engagement: 3.1,
    estimatedCost: 120000,
    brandFit: 82,
    status: "IDENTIFIED",
    whyFit: "Large audience, trusted voice in fitness community, review content performs well",
    campaignIdea: "Honest 30-day review of Velocity running performance",
  },
  {
    id: "cr4",
    name: "Priya Iyer",
    handle: "@priyaruns",
    platform: "Instagram",
    category: "Marathon / Running",
    audience: 67000,
    engagement: 8.4,
    estimatedCost: 12000,
    brandFit: 96,
    status: "CONTACTED",
    whyFit: "Micro-influencer with extremely high engagement, very authentic runner community",
    campaignIdea: "Training with Velocity — marathon prep series",
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: "t001",
    title: "Approve brand direction",
    description: "Review and approve the Velocity brand identity",
    owner: "Mira · Product & Brand Director",
    priority: "HIGH",
    status: "REVIEW",
    department: "PRODUCT",
    impact: "Unblocks website and content creation",
  },
  {
    id: "t002",
    title: "Finalize homepage design",
    description: "Complete the product homepage based on approved brand",
    owner: "Mira · Product & Brand Director",
    priority: "HIGH",
    dependency: "Approve brand direction",
    status: "IN_PROGRESS",
    department: "PRODUCT",
  },
  {
    id: "t003",
    title: "Approve launch pricing",
    description: "Review unit economics and approve ₹4,999 launch price",
    owner: "Noah · Operations Director",
    priority: "HIGH",
    status: "REVIEW",
    department: "OPERATIONS",
    impact: "Needed for campaign setup",
  },
  {
    id: "t004",
    title: "Finalize creator shortlist",
    description: "Review and approve top 10 creators for outreach",
    owner: "Ari · Growth Director",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    department: "GROWTH",
  },
  {
    id: "t005",
    title: "Launch Instagram page",
    description: "Set up and launch the official @velocityshoes account",
    owner: "Ari · Growth Director",
    priority: "HIGH",
    status: "PLANNED",
    department: "GROWTH",
  },
  {
    id: "t006",
    title: "Set up payment gateway",
    description: "Configure Razorpay for website checkout",
    owner: "Noah · Operations Director",
    priority: "HIGH",
    status: "PLANNED",
    department: "OPERATIONS",
  },
  {
    id: "t007",
    title: "Film first batch of content",
    description: "Create 10 reels for launch week",
    owner: "Ari · Growth Director",
    priority: "MEDIUM",
    status: "BACKLOG",
    department: "GROWTH",
  },
  {
    id: "t008",
    title: "Set up logistics partner",
    description: "Finalize Delhivery or Shiprocket partnership",
    owner: "Noah · Operations Director",
    priority: "MEDIUM",
    status: "PLANNED",
    department: "OPERATIONS",
  },
];

export const DEMO_DECISIONS: Decision[] = [
  {
    id: "d1",
    title: "Position brand as premium-accessible",
    description: "Velocity will be priced at ₹4,999 — premium feel, accessible price point for Gen Z",
    madeBy: "Nova · AI CEO + Mira · Product Director",
    reason: "Target audience values design and performance but is price-sensitive. ₹4,999 is aspirational but achievable for 18-28 urban Indians.",
    confidence: 82,
    impact: "HIGH",
    reversible: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2",
    title: "Go DTC-first, no marketplace",
    description: "Launch exclusively on velocityshoes.in — no Amazon or Flipkart in first 6 months",
    madeBy: "Nova · AI CEO + Noah · Operations Director",
    reason: "DTC preserves margin, builds brand equity, and allows data collection. Marketplaces commoditize positioning.",
    confidence: 78,
    impact: "HIGH",
    reversible: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3",
    title: "Creator-led launch strategy",
    description: "First 100 customers through micro-influencer seeding, not paid ads",
    madeBy: "Ari · Growth Director",
    reason: "Lower CAC, higher trust, better content generation. Gen Z trusts creators over ads.",
    confidence: 85,
    impact: "HIGH",
    reversible: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4",
    title: "Launch with 3 colorways only",
    description: "Black, White, and Clay — minimal SKU count for cleaner operations",
    madeBy: "Mira · Product Director + Noah · Operations Director",
    reason: "Fewer SKUs = simpler inventory, less capital tied up, faster to market",
    confidence: 91,
    impact: "MEDIUM",
    reversible: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_ACTIVITY: ActivityItem[] = [
  {
    id: "a1",
    agentId: "ceo",
    agentName: "Nova · Chief Executive Agent",
    message: "Breaking your idea into business requirements and assigning to the team.",
    timestamp: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    type: "info",
  },
  {
    id: "a2",
    agentId: "product",
    agentName: "Mira · Product & Brand Director",
    message: "Identified target customer: Gen Z urban runners, 18–28, metro cities.",
    timestamp: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    type: "completed",
  },
  {
    id: "a3",
    agentId: "product",
    agentName: "Mira · Product & Brand Director",
    message: "Analyzed 18 competitor brands. Positioning gap found: affordable premium running.",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    type: "completed",
  },
  {
    id: "a4",
    agentId: "product",
    agentName: "Mira · Product & Brand Director",
    message: "Brand name selected: Velocity. Tagline: 'Run your way.'",
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    type: "decision",
  },
  {
    id: "a5",
    agentId: "growth",
    agentName: "Ari · Growth Director",
    message: "Analyzing current short-form content patterns on Instagram and YouTube.",
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    type: "info",
  },
  {
    id: "a6",
    agentId: "growth",
    agentName: "Ari · Growth Director",
    message: "Generated 32 content ideas. Top format: POV reels (90% brand fit).",
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    type: "completed",
  },
  {
    id: "a7",
    agentId: "operations",
    agentName: "Noah · Operations Director",
    message: "Unit economics calculated. ₹4,999 price gives 52% gross margin.",
    timestamp: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    type: "completed",
  },
  {
    id: "a8",
    agentId: "ceo",
    agentName: "Nova · Chief Executive Agent",
    message: "Company ready. 4 approvals needed from you before launch.",
    timestamp: new Date().toISOString(),
    type: "decision",
  },
];

export const DEMO_OPERATIONS: OperationsArtifact = {
  businessModel: "Direct-to-consumer (DTC) premium running footwear. Revenue from product sales. Margin from premium pricing over COGS.",
  pricing: {
    sellingPrice: 4999,
    cogs: 1200,
    packaging: 150,
    shipping: 200,
    paymentFee: 100,
    cac: 400,
    returns: 150,
    otherCosts: 100,
  },
  unitEconomics: {
    grossMargin: 52,
    contributionMargin: 38,
    breakEven: 420,
    profitPerOrder: 1899,
    requiredOrders: 100,
  },
  launchPhases: [
    {
      id: "phase1",
      name: "Foundation",
      description: "Brand, product, website, and operations setup",
      startWeek: 1,
      endWeek: 3,
      status: "COMPLETED",
      tasks: [],
    },
    {
      id: "phase2",
      name: "Pre-Launch",
      description: "Creator seeding, content production, waitlist building",
      startWeek: 4,
      endWeek: 6,
      status: "IN_PROGRESS",
      tasks: [],
    },
    {
      id: "phase3",
      name: "Launch",
      description: "Go live, first 100 customers, creator content drops",
      startWeek: 7,
      endWeek: 8,
      status: "PLANNED",
      tasks: [],
    },
    {
      id: "phase4",
      name: "Optimization",
      description: "Review data, optimize CAC, improve conversion",
      startWeek: 9,
      endWeek: 12,
      status: "PLANNED",
      tasks: [],
    },
    {
      id: "phase5",
      name: "Scale",
      description: "Expand channels, add SKUs, grow to ₹10L+ MRR",
      startWeek: 13,
      endWeek: 24,
      status: "PLANNED",
      tasks: [],
    },
  ],
  status: "APPROVED",
};

export const DEMO_GROWTH: GrowthArtifact = {
  contentStrategy: "Creator-first content marketing. 80% organic (creator UGC + founder content), 20% paid amplification of winning content.",
  channels: ["Instagram", "YouTube", "WhatsApp", "Email"],
  contentIdeas: DEMO_CONTENT_IDEAS,
  trends: DEMO_TRENDS,
  creators: DEMO_CREATORS,
  status: "APPROVED",
};
